### ISSUE TITLE
Видалення сайту з списку

### ISSUE THREAD

**Issue by andreykko** [codeguida/ua-dev-list#6]
Пропоную видалити [it-ua](http://it-ua.info/) зі списку, так як це просто парсер хабру, який перекладає статті автомат. перекладачем і все.

**Comment by denysdovhan** [comment]
Я не заперечую, але й не підтримую. Сайт відповідає критаріям списку. Наше завдання лише надати список таких ресурсів, а користувачі вже самі визначаться чи корисний він для них.
